### ISSUE TITLE
Blacklist with comma

### ISSUE THREAD

**Issue by Graziella-Husson** [VisualDataWeb/LD-VOWL#5]
Hello !
I'm using LD-VOWL and some of the classes I would like to blacklist contains commas. Is it possible to escape the "," symbol? I tried with a "\" but it did not seem to work...
Thanks in advance for your help!

**Comment by steffen-l** [comment]
Not sure if I got you right: Commas belong to the reserved character set in URIs (see G.2 in http://www.ietf.org/rfc/rfc2396.txt ), so they shouldn't affect the blacklisted URIs. Or did I get you wrong?

**Comment by Graziella-Husson** [comment]
Ok, so it seems that my data is not really standard. Guess it's easier to change it than trying to escape the "," symbol. Thanks for your help!
