### ISSUE TITLE
Local proxy?

### ISSUE THREAD

**Issue by jindrichmynarz** [VisualDataWeb/LD-VOWL#6]
Is it possible or planned to enable running the tool with a local proxy for the queried SPARQL endpoints instead of the default <http://vowl.visualdataweb.org/ldvowl/proxy.php>? For example, it would be useful to be able to run a local proxy to access non-public SPARQL endpoints.

**Comment by marc92w** [comment]
Yes of course that's possible, you only have to provide the URL of your local proxy and pass it to the production build:

First create a config file named `production.conf.json` at the root level of this project and provide a proxy URL there, e.g.
```json
{
  "proxyUrl": "http://localhost/proxy.php"
}
```

Then run the script for the production build: `npm run-script deploy`

After that deploy the files in the `/dist` folder on your local server next to the proxy (same origin).

I used a small PHP script as a proxy which sends a request to the provided endpoint and returns the response. The target is provided as an additional parameter in the URL:
`endpoint=<URL-encoded endpoint URL>`

I just tested this using a docker container running PHP. If you have further questions feel free to ask.
