### ISSUE TITLE
config example

### ISSUE THREAD

**Issue by cristianvasquez** [VisualDataWeb/LD-VOWL#9]
Hello, 

trying to deploy locally, but fails with 

```
Error: Cannot find module './development.conf.json'
```

What could be an example development.conf.json file?

**Comment by marc92w** [comment]
You just have to provide a URL for the proxy in your `development.conf.json`, e.g. try
```javascript
{
  "proxyUrl": "http://localhost:8081"
}
```

**Comment by cristianvasquez** [comment]
Thanks for the response!
